# INPUT CHANGES HERE

os: 'os' # 'windows' or 'linux' or 'os'

# Define your output path:
patient_df_path: 'patient_data/patient_df.csv'
patient_note_path: 'patient_data/patient_notes.csv'
patient_output_dir: 'patient_data/patients/'
patient_label_path: 'patient_data/patient_records.csv'
edf_dir: 'patient_data/edfs/'
result_dir: 'patient_data/results/'
cmd_result_dir: 'patient_data/results/cmd/'
lang_tracking_dir: 'patient_data/results/lang_tracking/' 

# Define your input path
stimuli_dir: 'audio_data/lang_trials/'
sentences_path: 'audio_data/sentences/'
right_keep_path: 'audio_data/static/right_keep.mp3'
right_stop_path: 'audio_data/static/right_stop.mp3'
left_keep_path: 'audio_data/static/left_keep.mp3'
left_stop_path: 'audio_data/static/left_stop.mp3'
beep_path: 'audio_data/static/sample_beep.mp3'
loved_one_path: 'audio_data/static/'
male_control_path: 'audio_data/static/ControlStatement_male.wav'
female_control_path: 'audio_data/static/ControlStatement_female.wav'
motor_prompt_path: 'audio_data/prompts/motorcommandprompt.wav'
oddball_prompt_path: 'audio_data/prompts/oddballprompt.wav'