# config.yml

os: 'os'  # 'windows', 'linux', or 'os'

# === OUTPUT PATHS ===
edf_dir: 'data/edfs/'
result_dir: 'data/results/'

# === AUDIO INPUT PATHS ===
sentences_path: 'audio_data/sentences/'
right_keep_path: 'audio_data/static/right_keep.mp3'
right_stop_path: 'audio_data/static/right_stop.mp3'
left_keep_path: 'audio_data/static/left_keep.mp3'
left_stop_path: 'audio_data/static/left_stop.mp3'
beep_path: 'audio_data/static/sample_beep.mp3'
loved_one_path: 'audio_data/static/'
male_control_path: 'audio_data/static/ControlStatement_male.wav'
female_control_path: 'audio_data/static/ControlStatement_female.wav'
motor_prompt_path: 'audio_data/prompts/motorcommandprompt.wav'
oddball_prompt_path: 'audio_data/prompts/oddballprompt.wav'